apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-deployment
  template:
    metadata:
      labels:
        app: front-deployment
    spec:
      containers:
      - name: frontend
        image: hamdinh98/olympiqs-repo:web
        ports:
          - containerPort: 4000
        env:
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: CLIENT-ID
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: CLIENT-SECRET
          - name: PUBLIC_URL
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: PUBLIC_URL
          - name: MERCURE_PUBLISH_URL
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: MERCURE_PUBLISH_URL

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  labels:
    app: back-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-deployment
  template:
    metadata:
      labels:
        app: back-deployment
    spec:
      containers:
      - name: backend
        image: hamdinh98/olympiqs-repo:web
        ports:
          - containerPort: 4001
        env:
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: CLIENT-ID
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: CLIENT-SECRET
          - name: APP_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: APP_SECRET
          - name: RESET_PWD_TOKEN_TTL
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: RESET_PWD_TOKEN_TTL
          - name: ACCESS_TOKEN_TTL
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: ACCESS_TOKEN_TTL
          - name: APP_ENV
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: APP_ENV
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: HOST
          - name: ADMIN_HOST
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: HOST
          - name: PUBLIC_API_HOST
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: HOST
          - name: ORGANIZATION
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: ORGANIZATION
          - name: PUBLIC_ORGANIZATION
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: PUBLIC_ORGANIZATION
          - name: MONGODB_URL
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: MONGODB_URL
          - name: MONGODB_DB
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: MONGODB_DB
          - name: MONGODB_REPLICASET
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: MONGODB_REPLICASET
          - name: MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: MONGODB_USERNAME
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: MONGODB_PASSWORD
          - name: OAUTH2_PRIVATE_KEY
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: OAUTH2_PRIVATE_KEY
          - name: OAUTH2_PUBLIC_KEY
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: OAUTH2_PUBLIC_KEY

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-deployment
  template:
    metadata:
      labels:
        app: mongo-deployment
    spec:
      containers:
      - name: database
        image: mongo
        ports:
          - containerPort: 27019
        env:
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: MONGODB_ROOT_PASSWORD
          - name: MONGODB_REPLICA_SET_KEY
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: MONGODB_REPLICA_SET_KEY
          - name: MONGODB_REPLICA_SET_MODE
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: MONGODB_REPLICA_SET_MODE
          - name: MONGODB_REPLICA_SET_NAME
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: MONGODB_REPLICA_SET_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  selector:
    app: front-deployment
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  selector:
    app: back-deployment
  ports:
  - port: 4001
    targetPort: 4001
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo-service
spec:
    selector:
      app: mongo-deployment
    ports:
    - port: 27019
      targetPort: 27019
      protocol: TCP