apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: default
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImFHRnRaR2x1YURrNE9tUnZZMnRsY2pFeU13PT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson